# mini-singml, built by ix's tools: over mini-ml's parser, whose objects
# are languages/ml's (mini-mk there first)
TOP=../../..
DIR=kernel/singularity/singml
PROG=mini-singml
SRC=Description Output Safe Manifest CLI Main
GEN=
LIBUNITS=Ast Parser Lexer
LOCAL=`{ls *.ml *.mli}
<$TOP/mkfiles/mkconfig
LIBI=-I $TOP/languages/ml -I $B/languages/ml
LIBOBJS=$B/languages/ml/Ast.$O $B/languages/ml/Parser.$O $B/languages/ml/Lexer.$O
<$TOP/mkfiles/mkprog
