# mini-rc, built by ix's tools
TOP=..
DIR=shell
PROG=mini-rc
SRC=Ast Lexer Parser Glob Word Env Process Eval Builtin CLI Main
LOCAL=`{ls *.ml *.mli}
GEN=
LIBI=
LIBUNITS=
LIBOBJS=
<$TOP/mkfiles/mkconfig
<$TOP/mkfiles/mkprog
