# utilities/pipe, built by ix's tools: each program one file, with its
# start and its link (for Plan 9: mini-mk O=5 OS=plan9)
TOP=../..
<$TOP/mkfiles/mkconfig
D=$B/utilities/pipe
INCLUDES=-I . $STDI
LIBS=$STDOBJS $STDEND $TOP/mkfiles/mkconfig

all:V: $D/mini-tee $D/mini-tail $D/mini-xargs

$D/%.$O: %.ml
	mkdir -p $D
	$ML $INCLUDES -o $target $stem.ml
$D/mini-tee: $D/Tee.$O $LIBS
	$ML -start $STD $COMMONS Tee Std_exit -o $D/Tee.start.$O
	$LD $LDH -nofollow -o $target $D/Tee.start.$O $STDOBJS $D/Tee.$O $STDEND
$D/mini-tail: $D/Tail.$O $LIBS
	$ML -start $STD $COMMONS Tail Std_exit -o $D/Tail.start.$O
	$LD $LDH -nofollow -o $target $D/Tail.start.$O $STDOBJS $D/Tail.$O $STDEND
$D/mini-xargs: $D/Xargs.$O $LIBS
	$ML -start $STD $COMMONS Xargs Std_exit -o $D/Xargs.start.$O
	$LD $LDH -nofollow -o $target $D/Xargs.start.$O $STDOBJS $D/Xargs.$O $STDEND

clean:V:
	rm -rf $D
