# utilities/byte, built by ix's tools: each program one file, with its
# start and its link (for Plan 9: mini-mk O=5 OS=plan9)
TOP=../..
<$TOP/mkfiles/mkconfig
D=$B/utilities/byte
INCLUDES=-I . $STDI
LIBS=$STDOBJS $STDEND $TOP/mkfiles/mkconfig

all:V: $D/mini-xd

$D/%.$O: %.ml
	mkdir -p $D
	$ML $INCLUDES -o $target $stem.ml
$D/mini-xd: $D/Xd.$O $LIBS
	$ML -start $STD $COMMONS Xd Std_exit -o $D/Xd.start.$O
	$LD $LDH -nofollow -o $target $D/Xd.start.$O $STDOBJS $D/Xd.$O $STDEND

clean:V:
	rm -rf $D
