# mini-turbopascal in a terminal, built by ix's tools: the IDE
# (../editor), a session with no screen (../Keys), over mini-pascal
# (languages/pascal) and lib_terminal, with its Tty_unix; their units
# from their directories, by their names
TOP=../../..
DIR=editors/turbopascal/tty
PROG=mini-turbopascal-tty
T=$TOP/lib_terminal
R=$TOP/lib_playground/random
PAS=$TOP/languages/pascal
KIT=../editor
SRC=Lehmer Line_discipline Vt Talk Curses Tui Tty_unix Pcode Pascal_lexer Pascal_compile Pmachine Pdebug Pascal_disk Turbo_edit Turbo_debug Turbo_menus Turbo_update Turbo_view Tui_turbo Keys Main
LOCAL=`{ls *.ml ../*.ml ../*.mli ../editor/*.ml ../editor/*.mli ../../../lib_terminal/*.ml ../../../lib_terminal/*.mli ../../../lib_terminal/unix/*.ml ../../../lib_terminal/unix/*.mli ../../../languages/pascal/*.ml ../../../languages/pascal/*.mli ../../../lib_playground/random/*.ml ../../../lib_playground/random/*.mli}
GEN=
LIBI=-I .. -I ../editor -I ../../../lib_terminal -I ../../../lib_terminal/unix -I ../../../languages/pascal -I ../../../lib_playground/random
LIBUNITS=
LIBOBJS=
<$TOP/mkfiles/mkconfig
<$TOP/mkfiles/mkprog

# the others' units, by their names
$D/Lehmer.$O: $R/Lehmer.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $R/Lehmer.ml
$D/Line_discipline.$O: $T/Line_discipline.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $T/Line_discipline.ml
$D/Vt.$O: $T/Vt.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $T/Vt.ml
$D/Talk.$O: $T/Talk.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $T/Talk.ml
$D/Curses.$O: $T/Curses.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $T/Curses.ml
$D/Tui.$O: $T/Tui.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $T/Tui.ml
$D/Tty_unix.$O: $T/unix/Tty_unix.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $T/unix/Tty_unix.ml
$D/Pcode.$O: $PAS/Pcode.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $PAS/Pcode.ml
$D/Pascal_lexer.$O: $PAS/Pascal_lexer.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $PAS/Pascal_lexer.ml
$D/Pascal_compile.$O: $PAS/Pascal_compile.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $PAS/Pascal_compile.ml
$D/Pmachine.$O: $PAS/Pmachine.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $PAS/Pmachine.ml
$D/Pdebug.$O: $PAS/Pdebug.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $PAS/Pdebug.ml
$D/Pascal_disk.$O: $PAS/Pascal_disk.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $PAS/Pascal_disk.ml
$D/Turbo_edit.$O: $KIT/Turbo_edit.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $KIT/Turbo_edit.ml
$D/Turbo_debug.$O: $KIT/Turbo_debug.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $KIT/Turbo_debug.ml
$D/Turbo_menus.$O: $KIT/Turbo_menus.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $KIT/Turbo_menus.ml
$D/Turbo_update.$O: $KIT/Turbo_update.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $KIT/Turbo_update.ml
$D/Turbo_view.$O: $KIT/Turbo_view.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $KIT/Turbo_view.ml
$D/Tui_turbo.$O: $KIT/Tui_turbo.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $KIT/Tui_turbo.ml
$D/Keys.$O: ../Keys.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target ../Keys.ml
