# mini-ar, built by ix's tools
TOP=../..
DIR=linker/tools
PROG=mini-ar
SRC=Ar
LOCAL=`{ls *.ml}
GEN=
LIBI=-I ../../assembler -I ..
LIBUNITS=Asm Show_asm Link
<$TOP/mkfiles/mkconfig
LIBOBJS=$B/assembler/Asm.$O $B/assembler/Show_asm.$O $B/linker/Link.$O
<$TOP/mkfiles/mkprog
