# utilities/time, built by ix's tools: each program one file, with its
# start and its link (for Plan 9: mini-mk O=5 OS=plan9)
TOP=../..
<$TOP/mkfiles/mkconfig
D=$B/utilities/time
INCLUDES=-I . $STDI
LIBS=$STDOBJS $STDEND $TOP/mkfiles/mkconfig

all:V: $D/mini-date $D/mini-cal

$D/%.$O: %.ml
	mkdir -p $D
	$ML $INCLUDES -o $target $stem.ml
$D/mini-date: $D/Date.$O $LIBS
	$ML -start $STD $COMMONS Date Std_exit -o $D/Date.start.$O
	$LD $LDH -nofollow -o $target $D/Date.start.$O $STDOBJS $D/Date.$O $STDEND
$D/mini-cal: $D/Cal.$O $LIBS
	$ML -start $STD $COMMONS Cal Std_exit -o $D/Cal.start.$O
	$LD $LDH -nofollow -o $target $D/Cal.start.$O $STDOBJS $D/Cal.$O $STDEND

clean:V:
	rm -rf $D
