# mini-turbopascal for mini-9pi (mini-mk O=5 OS=plan9): turbopascal, the
# IDE (../../editor) in a window of mini-rio's, painted by the draw
# device (Window, over ../Cells and lib_graphics), over mini-pascal
# (languages/pascal) and lib_terminal; their units from their
# directories, by their names
TOP=../../../..
DIR=editors/turbopascal/hosts/draw
PROG=turbopascal
T=$TOP/lib_terminal
R=$TOP/lib_playground/random
PAS=$TOP/languages/pascal
KIT=../../editor
G=$TOP/lib_graphics
SRC=Lehmer Line_discipline Vt Talk Curses Tui Pcode Pascal_lexer Pascal_compile Pmachine Pdebug Pascal_disk Turbo_edit Turbo_debug Turbo_menus Turbo_update Turbo_view Tui_turbo Keys Point Rectangle Display Draw Font_default Font Mouse Keyboard Cells Window Main
LOCAL=`{ls *.ml *.mli ../*.ml ../*.mli ../../*.ml ../../*.mli ../../editor/*.ml ../../editor/*.mli ../../../../lib_terminal/*.ml ../../../../lib_terminal/*.mli ../../../../languages/pascal/*.ml ../../../../languages/pascal/*.mli ../../../../lib_playground/random/*.ml ../../../../lib_playground/random/*.mli ../../../../lib_graphics/*.ml ../../../../lib_graphics/*.mli}
GEN=
LIBI=-I .. -I ../.. -I ../../editor -I ../../../../lib_terminal -I ../../../../languages/pascal -I ../../../../lib_playground/random -I ../../../../lib_graphics
LIBUNITS=
LIBOBJS=
<$TOP/mkfiles/mkconfig
<$TOP/mkfiles/mkprog

# the others' units, by their names
$D/Lehmer.$O: $R/Lehmer.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $R/Lehmer.ml
$D/Line_discipline.$O: $T/Line_discipline.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $T/Line_discipline.ml
$D/Vt.$O: $T/Vt.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $T/Vt.ml
$D/Talk.$O: $T/Talk.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $T/Talk.ml
$D/Curses.$O: $T/Curses.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $T/Curses.ml
$D/Tui.$O: $T/Tui.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $T/Tui.ml
$D/Pcode.$O: $PAS/Pcode.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $PAS/Pcode.ml
$D/Pascal_lexer.$O: $PAS/Pascal_lexer.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $PAS/Pascal_lexer.ml
$D/Pascal_compile.$O: $PAS/Pascal_compile.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $PAS/Pascal_compile.ml
$D/Pmachine.$O: $PAS/Pmachine.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $PAS/Pmachine.ml
$D/Pdebug.$O: $PAS/Pdebug.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $PAS/Pdebug.ml
$D/Pascal_disk.$O: $PAS/Pascal_disk.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $PAS/Pascal_disk.ml
$D/Turbo_edit.$O: $KIT/Turbo_edit.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $KIT/Turbo_edit.ml
$D/Turbo_debug.$O: $KIT/Turbo_debug.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $KIT/Turbo_debug.ml
$D/Turbo_menus.$O: $KIT/Turbo_menus.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $KIT/Turbo_menus.ml
$D/Turbo_update.$O: $KIT/Turbo_update.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $KIT/Turbo_update.ml
$D/Turbo_view.$O: $KIT/Turbo_view.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $KIT/Turbo_view.ml
$D/Tui_turbo.$O: $KIT/Tui_turbo.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $KIT/Tui_turbo.ml
$D/Keys.$O: ../../Keys.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target ../../Keys.ml
$D/Point.$O: $G/Point.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $G/Point.ml
$D/Rectangle.$O: $G/Rectangle.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $G/Rectangle.ml
$D/Display.$O: $G/Display.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $G/Display.ml
$D/Draw.$O: $G/Draw.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $G/Draw.ml
$D/Font_default.$O: $G/Font_default.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $G/Font_default.ml
$D/Font.$O: $G/Font.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $G/Font.ml
$D/Mouse.$O: $G/Mouse.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $G/Mouse.ml
$D/Keyboard.$O: $G/Keyboard.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target $G/Keyboard.ml
$D/Cells.$O: ../Cells.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target ../Cells.ml
