(* The code generator shared by the machines (cgen.c, txt.c, swt.c,
 * com64.c of 5c and 7c): the labelling of the trees ([xcom]), the
 * expressions ([cgen], [boolgen] for conditions), the statements and
 * the switch ([codgen]'s gen).
 *
 * [xcom] labels each node bottom-up with its addressability -- what
 * can be an instruction's operand as it is -- and its Sethi-Ullman
 * complexity; cgen is a recursive descent that compiles the harder
 * operand first and stops at the addressable leaves. A condition
 * compiles to where the program counter goes, not to a value.
 *
 * 5c and 7c differ in more than their instructions: the [hooks] record
 * holds what else does (vlongs as calls on arm, 32-bit multiplies on
 * arm64, which operand an op= loads...), filled by Arm and Arm64. The
 * code is a few combinators ([op2], [op3], [compare]...) where 5c
 * spells each case out.
 *
 * References: Ken Thompson, "Plan 9 C Compilers", sections
 * "Addressability" (a node "labeled by consulting a table indexed by
 * the labels on the left and right subtrees") and "Code generation":
 * "Code is generated by recursive descent. The Sethi-Ullman complexity
 * completely guides the order. The addressability defines the leaves.";
 * and, on generating it from a machine description, "Since this code
 * generator is so small (less than 500 lines of C) and easy, it hardly
 * seems worth the effort." -- A. V. Aho, M. Ganapathi and S. W. K.
 * Tjiang, "Code generation using tree matching and dynamic programming"
 * (ACM TOPLAS 11(4), 1989), is that road not taken; R. Sethi and J. D.
 * Ullman, "The Generation of Optimal Code for Arithmetic Expressions"
 * (JACM 17(4), 1970), for [xcom]'s complexity, with a call "marked
 * infinite" (100); A. V. Aho, R. Sethi and J. D. Ullman, Compilers:
 * Principles, Techniques, and Tools (1986), chapter 8, whose boolean
 * code generator [boolgen] expands, by Thompson's account "with
 * extensive use of De Morgan's rule". *)

(* what differs between 5c's and 7c's generators, beyond the
 * instructions: set by the machine's module *)
type hooks = {
  sucopy : Tree.expr -> Tree.expr -> int -> unit;       (* a structure's copy *)
  table : Tree.expr -> Tree.expr -> Tree.expr -> int -> unit;  (* a switch's table: the value, a register, its range, the default *)
  fits : Tree.expr -> int -> bool;         (* an offset folded into n's load or store *)
  neg : Tree.expr -> Tree.expr -> unit;         (* to = -from *)
  mul32 : bool;                       (* a multiplier held in 32 bits (7c's mulcon) *)
  rsb : bool;                         (* c - x as a reverse subtract (5c) *)
  by_left : bool;                     (* x op y's registers typed as x, so shifts work (7c) *)
  com64 : bool;                       (* vlong operators as calls (5c) *)
  shifts : bool;                      (* shift-and-mask simplified, a constant compared on the right (7c) *)
  zero_arg : bool;                    (* a 0 argument stored as it is (7c) *)
  asop_load : bool;                   (* x op= y: y into the result's register, x loaded after (7c) *)
  indreg_ptr : bool;                  (* a register's address computed as a pointer (7c) *)
}

val hooks : hooks option ref

(* the addressability and complexity of the tree: a new tree *)
val xcom : Tree.expr -> Tree.expr

(* what the machines' modules build with: a move, an operation, a
 * comparison and its branch, a switch's table *)
val gmove : Tree.expr -> Tree.expr -> unit
val gopcode : Emit.gop -> Tree.expr option -> Tree.expr option -> Tree.expr option -> unit
val op2 : Tree.binop -> Tree.expr -> Tree.expr -> unit
val op3 : Tree.binop -> Tree.expr -> Tree.expr -> Tree.expr -> unit
val compare : ?tr:bool -> Tree.binop -> Tree.expr -> Tree.expr -> unit
val gcase : Tree.expr -> Tree.expr -> unit
val iconst : int -> Tree.expr

(* the address of n in a register, as an indirection; of nn as a
 * long's *)
val reglcgen : Tree.expr -> Tree.expr option -> Tree.expr
val reglpcgen : Tree.expr -> bool -> Tree.expr

(* a function's code: its name and its body *)
val codgen : Tree.sym -> Tree.stmt -> unit
