# lib_graphics's programs, for mini-9pi (mini-mk O=5 OS=plan9): the
# library's units, compiled here, then each program with its start and
# its link
TOP=../..
<$TOP/mkfiles/mkconfig
D=$B/lib_graphics/tests
INCLUDES=-I . -I .. $STDI
LIB=Point Rectangle Display Draw Font_default Font Mouse Keyboard Menu
LIBOBJS=${LIB:%=$D/%.$O}
LOCAL=`{ls *.ml ../*.ml ../*.mli}
LIBS=$LIBOBJS $STDOBJS $STDEND $TOP/mkfiles/mkconfig

all:V: $D/hellodraw $D/hellomenu

$D/%.$O: ../%.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target ../$stem.ml
$D/Hellodraw.$O: Hellodraw.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target Hellodraw.ml
$D/Hellomenu.$O: Hellomenu.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target Hellomenu.ml
$D/hellodraw: $D/Hellodraw.$O $LIBS
	$ML -start $STD $COMMONS $LIB Hellodraw Std_exit -o $D/Hellodraw.start.$O
	$LD $LDH -nofollow -o $target $D/Hellodraw.start.$O $STDOBJS $LIBOBJS $D/Hellodraw.$O $STDEND
$D/hellomenu: $D/Hellomenu.$O $LIBS
	$ML -start $STD $COMMONS $LIB Hellomenu Std_exit -o $D/Hellomenu.start.$O
	$LD $LDH -nofollow -o $target $D/Hellomenu.start.$O $STDOBJS $LIBOBJS $D/Hellomenu.$O $STDEND

clean:V:
	rm -rf $D
