# hellodraw, lib_graphics's first program, for mini-9pi (mini-mk O=5 OS=plan9),
# with the library's units
TOP=../..
DIR=lib_graphics/tests
PROG=hellodraw
SRC=Point Rectangle Display Draw Font_default Font Hellodraw
LOCAL=`{ls *.ml ../*.ml ../*.mli}
GEN=
LIBI=-I ..
LIBUNITS=
LIBOBJS=
<$TOP/mkfiles/mkconfig
<$TOP/mkfiles/mkprog
$D/Point.$O: ../Point.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target ../Point.ml
$D/Rectangle.$O: ../Rectangle.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target ../Rectangle.ml
$D/Display.$O: ../Display.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target ../Display.ml
$D/Draw.$O: ../Draw.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target ../Draw.ml
$D/Font_default.$O: ../Font_default.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target ../Font_default.ml
$D/Font.$O: ../Font.ml $LOCAL
	mkdir -p $D
	$ML $INCLUDES -o $target ../Font.ml
