# networking's programs, built by ix's tools: the libraries' units
# (lib_crypto, lib_networking's tcp, tls and http), compiled here, each
# found by its name in their directories, then a program with its start
# and its link
TOP=..
<$TOP/mkfiles/mkconfig
D=$B/networking
DIRS=. ../lib_compression ../lib_crypto ../lib_networking/tcp ../lib_networking/tls ../lib_networking/http
INCLUDES=-I . -I ../lib_compression -I ../lib_crypto -I ../lib_networking/tcp -I ../lib_networking/tls -I ../lib_networking/http $STDI
# (each before the ones that name it)
CRYPTO=Sha256 Sha512 Hmac Hkdf Chacha20 Poly1305 Chacha20_poly1305 Aes Gcm Bignum X25519 Ecdsa Rsa
NET=Dns Tcp Base64 Civil Clock Asn1 Pem X509 Tls13 Tls_client Url Urlencoded Zlib Http Cookie Cookie_jar Keep_alive Http_client
LIB=$CRYPTO $NET
LIBOBJS=${LIB:%=$D/%.$O}
LOCAL=`{ls *.ml ../lib_compression/Zlib.ml ../lib_compression/Zlib.mli ../lib_crypto/*.ml ../lib_crypto/*.mli ../lib_networking/*/*.ml ../lib_networking/*/*.mli}
LIBS=$LIBOBJS $STDOBJS $STDEND $TOP/mkfiles/mkconfig

all:V: $D/mini-curl $D/mini-httpd

$D/%.$O: $LOCAL
	mkdir -p $D
	for d in $DIRS; do [ -f $d/$stem.ml ] && f=$d/$stem.ml; done
	$ML $INCLUDES -o $target $f
$D/mini-curl: $D/Curl.$O $LIBS
	$ML -start $STD $COMMONS $LIB Curl Std_exit -o $D/Curl.start.$O
	$LD $LDH -nofollow -o $target $D/Curl.start.$O $STDOBJS $LIBOBJS $D/Curl.$O $STDEND
$D/mini-httpd: $D/Httpd.$O $LIBS
	$ML -start $STD $COMMONS $LIB Httpd Std_exit -o $D/Httpd.start.$O
	$LD $LDH -nofollow -o $target $D/Httpd.start.$O $STDOBJS $LIBOBJS $D/Httpd.$O $STDEND

clean:V:
	rm -rf $D
