# mini-chidb, built by ix's tools: its lexer by mini-lex, its grammar by
# mini-yacc
TOP=..
DIR=database
PROG=mini-chidb
SRC=Pager Record Btree Cursor Dbm Dbmfile Ast Show_ast Parser Lexer Sql Schema Codegen Optimizer Shell CLI Main
LOCAL=`{ls *.ml *.mli *.mly *.mll}
LIBI=
LIBUNITS=
LIBOBJS=
<$TOP/mkfiles/mkconfig
GEN=$B/database/Parser.ml $B/database/Lexer.ml
<$TOP/mkfiles/mkprog

# the units mini-yacc and mini-lex made, by their names
$D/Parser.$O: $D/Parser.ml $LOCAL
	$ML $INCLUDES -o $target $D/Parser.ml
$D/Lexer.$O: $D/Lexer.ml $D/Parser.ml $LOCAL
	$ML $INCLUDES -o $target $D/Lexer.ml
