# mini-asm, built by ix's tools
TOP=..
DIR=assembler
PROG=mini-asm
SRC=Asm Show_asm Lexer_asm Parser_asm CLI Main
GEN=
LIBI=
LIBUNITS=
LIBOBJS=
LOCAL=`{ls *.ml *.mli}
<$TOP/mkfiles/mkconfig
<$TOP/mkfiles/mkprog
