# utilities/process, built by ix's tools: each program one file, with its
# start and its link (for Plan 9: mini-mk O=5 OS=plan9)
TOP=../..
<$TOP/mkfiles/mkconfig
D=$B/utilities/process
INCLUDES=-I . $STDI
LIBS=$STDOBJS $STDEND $TOP/mkfiles/mkconfig

all:V: $D/mini-sleep $D/mini-ps $D/mini-time $D/mini-free

$D/%.$O: %.ml
	mkdir -p $D
	$ML $INCLUDES -o $target $stem.ml
$D/mini-sleep: $D/Sleep.$O $LIBS
	$ML -start $STD $COMMONS Sleep Std_exit -o $D/Sleep.start.$O
	$LD $LDH -nofollow -o $target $D/Sleep.start.$O $STDOBJS $D/Sleep.$O $STDEND
$D/mini-ps: $D/Ps.$O $LIBS
	$ML -start $STD $COMMONS Ps Std_exit -o $D/Ps.start.$O
	$LD $LDH -nofollow -o $target $D/Ps.start.$O $STDOBJS $D/Ps.$O $STDEND
$D/mini-time: $D/Time.$O $LIBS
	$ML -start $STD $COMMONS Time Std_exit -o $D/Time.start.$O
	$LD $LDH -nofollow -o $target $D/Time.start.$O $STDOBJS $D/Time.$O $STDEND
$D/mini-free: $D/Free.$O $LIBS
	$ML -start $STD $COMMONS Free Std_exit -o $D/Free.start.$O
	$LD $LDH -nofollow -o $target $D/Free.start.$O $STDOBJS $D/Free.$O $STDEND

clean:V:
	rm -rf $D
