# mini-ed, built by ix's tools
TOP=..
DIR=editor
PROG=mini-ed
SRC=Text Input Out Address Command CLI Main
LOCAL=`{ls *.ml *.mli}
GEN=
LIBI=
LIBUNITS=
LIBOBJS=
<$TOP/mkfiles/mkconfig
<$TOP/mkfiles/mkprog
