# mini-scheme, built by ix's tools
TOP=../..
DIR=languages/scheme
PROG=mini-scheme
SRC=Sexpr Sexpr_read Scheme_image Scheme Scheme_syntax Scheme_prims Scheme_prelude Scheme_map Scheme_eval Scheme_step CLI Main
LOCAL=`{ls *.ml *.mli}
GEN=
LIBI=
LIBUNITS=
LIBOBJS=
<$TOP/mkfiles/mkconfig
<$TOP/mkfiles/mkprog
