# utilities/compare, built by ix's tools: each program one file, with its
# start and its link (for Plan 9: mini-mk O=5 OS=plan9)
TOP=../..
<$TOP/mkfiles/mkconfig
D=$B/utilities/compare
INCLUDES=-I . $STDI
LIBS=$STDOBJS $STDEND $TOP/mkfiles/mkconfig

all:V: $D/mini-cmp

$D/%.$O: %.ml
	mkdir -p $D
	$ML $INCLUDES -o $target $stem.ml
$D/mini-cmp: $D/Cmp.$O $LIBS
	$ML -start $STD $COMMONS Cmp Std_exit -o $D/Cmp.start.$O
	$LD $LDH -nofollow -o $target $D/Cmp.start.$O $STDOBJS $D/Cmp.$O $STDEND

clean:V:
	rm -rf $D
