(executable
 (name TinyBuildSystem)
 (public_name tinybuild)
 (package ix)
 (modules TinyBuildSystem)
 (libraries unix caps))

(executable
 (name TinyShell)
 (public_name tinyshell)
 (package ix)
 (modules TinyShell)
 (libraries unix caps))

(executable
 (name TinyEditor)
 (public_name tinyeditor)
 (package ix)
 (modules TinyEditor)
 (libraries unix))
