(executable
 (name TinyBuildSystem)
 (public_name tiny-build)
 (package ix)
 (modules TinyBuildSystem)
 (libraries ix_core fpath unix caps))

(executable
 (name TinyShell)
 (public_name tiny-shell)
 (package ix)
 (modules TinyShell)
 (libraries ix_core fpath unix caps))

(executable
 (name TinyEditor)
 (public_name tiny-editor)
 (package ix)
 (modules TinyEditor)
 (libraries unix))

(executable
 (name TinyAssembler)
 (public_name tiny-assembler)
 (package ix)
 (modules TinyAssembler)
 (libraries ix_core fpath caps))

(executable
 (name TinyC)
 (public_name tiny-c)
 (package ix)
 (modules TinyC))

(executable
 (name TinyDatabase)
 (public_name tiny-db)
 (package ix)
 (modules TinyDatabase)
 (libraries unix caps))

(executable
 (name TinyVCS)
 (public_name tiny-vcs)
 (package ix)
 (modules TinyVCS)
 (libraries ix_core unix caps ix_security ix_compression))

(executable
 (name TinyArm)
 (public_name tiny-arm)
 (package ix)
 (modules TinyArm)
 (libraries ix_core fpath caps))

(executable
 (name TinyCPU)
 (public_name tiny-cpu)
 (package ix)
 (modules TinyCPU)
 (libraries ix_core fpath caps))
