# The tiny programs, built by ix's tools: each one file (and for the
# CPUs their library's, for tiny-vcs SHA-1 and zlib), with its start
# and its link. TinyKernel.ml is not here: tiny-ml compiles it, for
# tiny-machine.
#
# Their library is m-ix's, lib_core/ (with mini-git's SHA-1 and zlib,
# compiled there), or t-ix's own with mini-mk LIB=tiny: TinyLib/ocaml/,
# the modules the tiny programs name and the functions they call
# (TinyLib/README.md), its objects and the programs under _mk/$O/tinylib.
# mini-ml's runtime and the C library under it are lib_core's for both.
TOP=..
<$TOP/mkfiles/mkconfig
LIB=core
D=`{case $LIB in tiny) echo $B/tinylib;; *) echo $B/tiny;; esac}
# TinyLib's units, in the order they are linked and initialized
# (lib_core/units.txt's, then commons/'s)
TSTD=Pervasives Int32 Int64 Seq List Char String Bytes Array Sys Hashtbl Filename Obj Queue \
 Buffer Marshal Printf Format Arg Digest Option Int Float Fun \
 In_channel Out_channel Fpath Cap CapSys CapStdlib Logs Logs_fmt Unix CapUnix \
 Common Console Logging Procs Fpath_ Chan FS
TL=$D/lib
TUNITS=${TSTD:%=$TL/%.$O}
# (SHA-1 and zlib: mini-git's objects, or TinyLib's)
V=`{case $LIB in tiny) echo $TL;; *) echo $B/version_control;; esac}
INCLUDES=`{case $LIB in tiny) echo -I . -I TinyLib/ocaml;; *) echo -I . -I ../lib_crypto -I ../lib_compression $STDI;; esac}
START=`{case $LIB in tiny) echo $ML -start $TSTD;; *) echo $ML -start $STD $COMMONS;; esac}
STDOBJS=`{case $LIB in tiny) echo $TL/TinyLib.a;; *) echo $STDOBJS;; esac}
STDEND=`{case $LIB in tiny) echo $TL/std_exit.$O $L/runtime.$O $L/libc.a;; *) echo $STDEND;; esac}
LINK=$LD -H7 -nofollow
LIBS=$STDOBJS $STDEND $TOP/mkfiles/mkconfig
PROGS=tiny-build tiny-shell tiny-editor tiny-assembler tiny-c tiny-ml tiny-db tiny-vcs tiny-arm tiny-pi tiny-cpu tiny-machine tiny-mkfs

all:V: ${PROGS:%=$D/%}

# (each unit alone: none names another, but the CPUs their library)
$D/%.$O: %.ml
	mkdir -p $D
	$ML $INCLUDES -o $target $stem.ml

# (TinyLib's, with LIB=tiny)
$TL/%.$O: TinyLib/ocaml/%.ml
	mkdir -p $TL
	$ML -I TinyLib/ocaml -o $target TinyLib/ocaml/$stem.ml
$TL/TinyLib.a: $TUNITS
	rm -f $target
	$AR u $target $TUNITS
$D/TinyCPUArm.$O $D/TinyMachinePi.$O: TinyLibArm.ml
$D/TinyCPU.$O $D/TinyMachine.$O: TinyLibCPU.ml

$D/tiny-build: $D/TinyBuildSystem.$O $LIBS
	$START TinyBuildSystem Std_exit -o $D/TinyBuildSystem.start.$O
	$LINK -o $target $D/TinyBuildSystem.start.$O $STDOBJS $D/TinyBuildSystem.$O $STDEND
$D/tiny-shell: $D/TinyShell.$O $LIBS
	$START TinyShell Std_exit -o $D/TinyShell.start.$O
	$LINK -o $target $D/TinyShell.start.$O $STDOBJS $D/TinyShell.$O $STDEND
$D/tiny-editor: $D/TinyEditor.$O $LIBS
	$START TinyEditor Std_exit -o $D/TinyEditor.start.$O
	$LINK -o $target $D/TinyEditor.start.$O $STDOBJS $D/TinyEditor.$O $STDEND
$D/tiny-assembler: $D/TinyAssembler.$O $LIBS
	$START TinyAssembler Std_exit -o $D/TinyAssembler.start.$O
	$LINK -o $target $D/TinyAssembler.start.$O $STDOBJS $D/TinyAssembler.$O $STDEND
$D/tiny-c: $D/TinyC.$O $LIBS
	$START TinyC Std_exit -o $D/TinyC.start.$O
	$LINK -o $target $D/TinyC.start.$O $STDOBJS $D/TinyC.$O $STDEND
$D/tiny-ml: $D/TinyML.$O $LIBS
	$START TinyML Std_exit -o $D/TinyML.start.$O
	$LINK -o $target $D/TinyML.start.$O $STDOBJS $D/TinyML.$O $STDEND
$D/tiny-db: $D/TinyDatabase.$O $LIBS
	$START TinyDatabase Std_exit -o $D/TinyDatabase.start.$O
	$LINK -o $target $D/TinyDatabase.start.$O $STDOBJS $D/TinyDatabase.$O $STDEND
$D/tiny-vcs: $V/Sha1.$O $V/Zlib.$O $D/TinyVCS.$O $LIBS
	$START Sha1 Zlib TinyVCS Std_exit -o $D/TinyVCS.start.$O
	$LINK -o $target $D/TinyVCS.start.$O $STDOBJS $V/Sha1.$O $V/Zlib.$O $D/TinyVCS.$O $STDEND
$D/tiny-arm: $D/TinyLibArm.$O $D/TinyCPUArm.$O $LIBS
	$START TinyLibArm TinyCPUArm Std_exit -o $D/TinyCPUArm.start.$O
	$LINK -o $target $D/TinyCPUArm.start.$O $STDOBJS $D/TinyLibArm.$O $D/TinyCPUArm.$O $STDEND
$D/tiny-pi: $D/TinyLibArm.$O $D/TinyMachinePi.$O $LIBS
	$START TinyLibArm TinyMachinePi Std_exit -o $D/TinyMachinePi.start.$O
	$LINK -o $target $D/TinyMachinePi.start.$O $STDOBJS $D/TinyLibArm.$O $D/TinyMachinePi.$O $STDEND
$D/tiny-cpu: $D/TinyLibCPU.$O $D/TinyCPU.$O $LIBS
	$START TinyLibCPU TinyCPU Std_exit -o $D/TinyCPU.start.$O
	$LINK -o $target $D/TinyCPU.start.$O $STDOBJS $D/TinyLibCPU.$O $D/TinyCPU.$O $STDEND
$D/tiny-machine: $D/TinyLibCPU.$O $D/TinyMachine.$O $LIBS
	$START TinyLibCPU TinyMachine Std_exit -o $D/TinyMachine.start.$O
	$LINK -o $target $D/TinyMachine.start.$O $STDOBJS $D/TinyLibCPU.$O $D/TinyMachine.$O $STDEND
$D/tiny-mkfs: $D/TinyMkfs.$O $LIBS
	$START TinyMkfs Std_exit -o $D/TinyMkfs.start.$O
	$LINK -o $target $D/TinyMkfs.start.$O $STDOBJS $D/TinyMkfs.$O $STDEND

clean:V:
	rm -rf $D
