# utilities/misc, built by ix's tools: each program one file, with its
# start and its link (for Plan 9: mini-mk O=5 OS=plan9)
TOP=../..
<$TOP/mkfiles/mkconfig
D=$B/utilities/misc
INCLUDES=-I . $STDI
LIBS=$STDOBJS $STDEND $TOP/mkfiles/mkconfig

all:V: $D/mini-echo

$D/%.$O: %.ml
	mkdir -p $D
	$ML $INCLUDES -o $target $stem.ml
$D/mini-echo: $D/Echo.$O $LIBS
	$ML -start $STD $COMMONS Echo Std_exit -o $D/Echo.start.$O
	$LD $LDH -nofollow -o $target $D/Echo.start.$O $STDOBJS $D/Echo.$O $STDEND

clean:V:
	rm -rf $D
