(* The code generator shared by the machines (cgen.c, txt.c, swt.c,
 * com64.c of 5c and 7c): the labelling of the trees ([xcom]), the
 * expressions ([cgen], [boolgen] for conditions), the statements and
 * the switch ([codgen]'s gen).
 *
 * [xcom] labels each node bottom-up with its addressability -- what
 * can be an instruction's operand as it is -- and its Sethi-Ullman
 * complexity; cgen is a recursive descent that compiles the harder
 * operand first and stops at the addressable leaves. A condition
 * compiles to where the program counter goes, not to a value.
 *
 * 5c and 7c differ in more than their instructions: the [hooks] record
 * holds what else does (vlongs as calls on arm, 32-bit multiplies on
 * arm64, which operand an op= loads...), filled by Arm and Arm64. The
 * code is a few combinators ([op2], [op3], [compare]...) where 5c
 * spells each case out.
 *
 * References: Ken Thompson, "Plan 9 C Compilers", sections
 * "Addressability" (a node "labeled by consulting a table indexed by
 * the labels on the left and right subtrees") and "Code generation":
 * "Code is generated by recursive descent. The Sethi-Ullman complexity
 * completely guides the order. The addressability defines the leaves.";
 * and, on generating it from a machine description, "Since this code
 * generator is so small (less than 500 lines of C) and easy, it hardly
 * seems worth the effort." -- A. V. Aho, M. Ganapathi and S. W. K.
 * Tjiang, "Code generation using tree matching and dynamic programming"
 * (ACM TOPLAS 11(4), 1989), is that road not taken; R. Sethi and J. D.
 * Ullman, "The Generation of Optimal Code for Arithmetic Expressions"
 * (JACM 17(4), 1970), for [xcom]'s complexity, with a call "marked
 * infinite" (100); A. V. Aho, R. Sethi and J. D. Ullman, Compilers:
 * Principles, Techniques, and Tools (1986), chapter 8, whose boolean
 * code generator [boolgen] expands, by Thompson's account "with
 * extensive use of De Morgan's rule". *)

(* what 5c and 7c do differently, beyond the instructions *)
type hooks = {
  sucopy : Tree.node -> Tree.node -> int -> unit;
  table :
    Tree.node -> Tree.node -> Tree.node -> int -> unit;
  fits : Tree.node -> int -> bool;
  neg : Tree.node -> Tree.node -> unit;
  mul32 : bool;
  rsb : bool;
  by_left : bool;
  com64 : bool;
  shifts : bool;
  zero_arg : bool;
  asop_load : bool;
  indreg_ptr : bool;
}

val hooks : hooks option ref

(* the addressability and complexity of the tree *)
val xcom : Tree.node -> unit

val gmove : Tree.node -> Tree.node -> unit

val gopcode :
  Tree.op ->
  Tree.node option ->
  Tree.node option -> Tree.node option -> unit

val op2 : Tree.op -> Tree.node -> Tree.node -> unit

val op3 :
  Tree.op ->
  Tree.node -> Tree.node -> Tree.node -> unit

val compare :
  ?tr:bool -> Tree.op -> Tree.node -> Tree.node -> unit

val iconst : int -> Tree.node

val reglcgen : Tree.node -> Tree.node option -> Tree.node

val reglpcgen : Tree.node -> bool -> Tree.node

type case = { cval : int64; cdef : bool; clabel : int; cisv : bool; }

(* a function's code: its name's node and its body *)
val codgen : Tree.node -> Tree.node -> unit
