# utilities/namespace, built by ix's tools: each program one file, with its
# start and its link (for Plan 9: mini-mk O=5 OS=plan9)
TOP=../..
<$TOP/mkfiles/mkconfig
D=$B/utilities/namespace
INCLUDES=-I . $STDI
LIBS=$STDOBJS $STDEND $TOP/mkfiles/mkconfig

all:V: $D/mini-bind $D/mini-mount

$D/%.$O: %.ml
	mkdir -p $D
	$ML $INCLUDES -o $target $stem.ml
$D/mini-bind: $D/Bind.$O $LIBS
	$ML -start $STD $COMMONS Bind Std_exit -o $D/Bind.start.$O
	$LD $LDH -nofollow -o $target $D/Bind.start.$O $STDOBJS $D/Bind.$O $STDEND
$D/mini-mount: $D/Mount.$O $LIBS
	$ML -start $STD $COMMONS Mount Std_exit -o $D/Mount.start.$O
	$LD $LDH -nofollow -o $target $D/Mount.start.$O $STDOBJS $D/Mount.$O $STDEND

clean:V:
	rm -rf $D
