#!/usr/bin/env python3
# Claude Code
# Copyright (C) 2026 Yoann Padioleau. LGPL 2.1: see license.txt.
#
# The OCaml pixels' data (lib_graphics/ocaml, PIXEL=ocaml), from
# principia's C where it is data, not code: libmemdraw/cmap.c's default
# colour map (mkcmap.c's output: cmap2rgb, 256 colours; rgb2cmap, 4096
# entries by 4-bit red, green, blue) and libdraw/defont.c's defontdata
# (lucm/latin1.9, the default font, uncompressed). Written as OCaml
# strings: DIR/Memdata.ml, and its interface.
#
# Usage: mkpixdata.py PRINCIPIA DIR

import os, re, sys

p, d = sys.argv[1], sys.argv[2]
gfx = os.path.join(p, "lib_graphics")

def numbers(text):
    return [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]+)", text)]

cmap = numbers(open(os.path.join(gfx, "libmemdraw/cmap.c")).read().split("cmap2rgb", 1)[1])
assert len(cmap) >= 768 + 4096, len(cmap)
defont = open(os.path.join(gfx, "libdraw/defont.c")).read()
defont = numbers(defont[defont.index("defontdata[]"):].split("};", 1)[0])

def literal(name, bs):
    lines = ["\"" + "".join("\\%03d" % b for b in bs[i:i + 32]) + "\"" for i in range(0, len(bs), 32)]
    return "let %s = String.concat \"\" [\n  %s ]\n" % (name, ";\n  ".join(lines))

os.makedirs(d, exist_ok=True)
with open(os.path.join(d, "Memdata.ml"), "w") as f:
    f.write("(* generated by conf/mkpixdata.py from principia's cmap.c and defont.c *)\n")
    f.write(literal("cmap2rgb", cmap[:768]))
    f.write(literal("rgb2cmap", cmap[768:768 + 4096]))
    f.write(literal("defont", defont))
with open(os.path.join(d, "Memdata.mli"), "w") as f:
    f.write("(* generated by conf/mkpixdata.py: the default colour map (cmap2rgb: 256\n"
            " * colours' r, g, b; rgb2cmap: by 4-bit r, g, b), the default font *)\n")
    f.write("val cmap2rgb : string\nval rgb2cmap : string\nval defont : string\n")
