# utilities/files, built by ix's tools: each program one file, with its
# start and its link (for Plan 9: mini-mk O=5 OS=plan9)
TOP=../..
<$TOP/mkfiles/mkconfig
D=$B/utilities/files
INCLUDES=-I . $STDI
LIBS=$STDOBJS $STDEND $TOP/mkfiles/mkconfig

all:V: $D/mini-cat $D/mini-ls $D/mini-pwd $D/mini-mkdir $D/mini-rm $D/mini-cp $D/mini-mv $D/mini-touch $D/mini-chmod $D/mini-mtime

$D/%.$O: %.ml
	mkdir -p $D
	$ML $INCLUDES -o $target $stem.ml
$D/mini-cat: $D/Cat.$O $LIBS
	$ML -start $STD $COMMONS Cat Std_exit -o $D/Cat.start.$O
	$LD $LDH -nofollow -o $target $D/Cat.start.$O $STDOBJS $D/Cat.$O $STDEND
$D/mini-ls: $D/Ls.$O $LIBS
	$ML -start $STD $COMMONS Ls Std_exit -o $D/Ls.start.$O
	$LD $LDH -nofollow -o $target $D/Ls.start.$O $STDOBJS $D/Ls.$O $STDEND
$D/mini-pwd: $D/Pwd.$O $LIBS
	$ML -start $STD $COMMONS Pwd Std_exit -o $D/Pwd.start.$O
	$LD $LDH -nofollow -o $target $D/Pwd.start.$O $STDOBJS $D/Pwd.$O $STDEND
$D/mini-mkdir: $D/Mkdir.$O $LIBS
	$ML -start $STD $COMMONS Mkdir Std_exit -o $D/Mkdir.start.$O
	$LD $LDH -nofollow -o $target $D/Mkdir.start.$O $STDOBJS $D/Mkdir.$O $STDEND
$D/mini-rm: $D/Rm.$O $LIBS
	$ML -start $STD $COMMONS Rm Std_exit -o $D/Rm.start.$O
	$LD $LDH -nofollow -o $target $D/Rm.start.$O $STDOBJS $D/Rm.$O $STDEND
$D/mini-cp: $D/Cp.$O $LIBS
	$ML -start $STD $COMMONS Cp Std_exit -o $D/Cp.start.$O
	$LD $LDH -nofollow -o $target $D/Cp.start.$O $STDOBJS $D/Cp.$O $STDEND
$D/mini-mv: $D/Mv.$O $LIBS
	$ML -start $STD $COMMONS Mv Std_exit -o $D/Mv.start.$O
	$LD $LDH -nofollow -o $target $D/Mv.start.$O $STDOBJS $D/Mv.$O $STDEND
$D/mini-touch: $D/Touch.$O $LIBS
	$ML -start $STD $COMMONS Touch Std_exit -o $D/Touch.start.$O
	$LD $LDH -nofollow -o $target $D/Touch.start.$O $STDOBJS $D/Touch.$O $STDEND
$D/mini-chmod: $D/Chmod.$O $LIBS
	$ML -start $STD $COMMONS Chmod Std_exit -o $D/Chmod.start.$O
	$LD $LDH -nofollow -o $target $D/Chmod.start.$O $STDOBJS $D/Chmod.$O $STDEND
$D/mini-mtime: $D/Mtime.$O $LIBS
	$ML -start $STD $COMMONS Mtime Std_exit -o $D/Mtime.start.$O
	$LD $LDH -nofollow -o $target $D/Mtime.start.$O $STDOBJS $D/Mtime.$O $STDEND

clean:V:
	rm -rf $D
