# kernel/tools, built by ix's tools: each program one file, with its
# start and its link
TOP=../..
<$TOP/mkfiles/mkconfig
D=$B/kernel/tools
INCLUDES=-I . $STDI
LIBS=$STDOBJS $STDEND $TOP/mkfiles/mkconfig

all:V: $D/mini-mkbootdir $D/mini-mkcard

$D/%.$O: %.ml
	mkdir -p $D
	$ML $INCLUDES -o $target $stem.ml
$D/mini-mkbootdir: $D/Mkbootdir.$O $LIBS
	$ML -start $STD $COMMONS Mkbootdir Std_exit -o $D/Mkbootdir.start.$O
	$LD $LDH -nofollow -o $target $D/Mkbootdir.start.$O $STDOBJS $D/Mkbootdir.$O $STDEND
$D/mini-mkcard: $D/Mkcard.$O $LIBS
	$ML -start $STD $COMMONS Mkcard Std_exit -o $D/Mkcard.start.$O
	$LD $LDH -nofollow -o $target $D/Mkcard.start.$O $STDOBJS $D/Mkcard.$O $STDEND

clean:V:
	rm -rf $D
