#!/usr/bin/env python3
# Claude Code
# Copyright (C) 2026 Yoann Padioleau. LGPL 2.1: see license.txt.
#
# Font_default.ml, from principia's lib_graphics/libdraw/defont.c
# (Plan 9's default font, lucm/latin1.9, as bytes in C): the same
# bytes as an OCaml string. Run once; its output is in the repository
# (the build does not run this, nor need principia).
#
# Usage: lib_graphics/tools/defont.py PRINCIPIA > lib_graphics/Font_default.ml

import os, re, sys

text = open(os.path.join(sys.argv[1], "lib_graphics/libdraw/defont.c")).read()
data = [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]+)", text[text.index("defontdata[]"):].split("};", 1)[0])]
print("(* Generated by tools/defont.py from principia's lib_graphics/libdraw/defont.c:")
print(" * Plan 9's default font (lucm/latin1.9; Lucida Sans Typewriter, Bigelow &")
print(" * Holmes's, as Plan 9 gives it: lib_graphics/README.md), %d bytes. Font" % len(data))
print(" * reads it: an image's header and pixels, then a subfont's header and its")
print(" * characters. *)")
print("let data = String.concat \"\" [")
for i in range(0, len(data), 32):
    print("  \"" + "".join("\\%03d" % b for b in data[i:i + 32]) + "\";")
print("]")
