; the unit tests of lib_graphics/images and of Blit (Testo), dune's
; only: the author's playground's Unit_png (over pngsuite/, Willem van
; Schaik's PngSuite, a subset, its licence beside it), Unit_jpeg (over
; jpegs/, the playground's own and libjpeg's pixels of each:
; make_jpegs.py there), Unit_gif (over gifs/, the playground's own:
; make_gifs.py there) and Unit_blit
(executable
 (name Test)
 (libraries ix_graphics_images ix_graphics_core ix_graphics_geometry ix_compression ix_core caps fpath unix alcotest testo))
