# mini-bc, built by ix's tools: its lexer by mini-lex, its grammar by
# mini-yacc; mini-dc's machine is what runs its programs (dc/ first)
TOP=../../..
DIR=utilities/calc/bc
PROG=mini-bc
SRC=State Parser Lexer Bclib CLI Main
LOCAL=`{ls *.ml *.mli *.mly *.mll ../dc/Dc.mli ../dc/Num.mli}
LIBI=-I ../dc
LIBUNITS=Num Dc
<$TOP/mkfiles/mkconfig
LIBOBJS=$B/utilities/calc/dc/Num.$O $B/utilities/calc/dc/Dc.$O
GEN=$B/utilities/calc/bc/Parser.ml $B/utilities/calc/bc/Lexer.ml
<$TOP/mkfiles/mkprog

# the units mini-yacc and mini-lex made, by their names
$D/Parser.$O: $D/Parser.ml $LOCAL
	$ML $INCLUDES -o $target $D/Parser.ml
$D/Lexer.$O: $D/Lexer.ml $D/Parser.ml $LOCAL
	$ML $INCLUDES -o $target $D/Lexer.ml
