(library
 (name ix_raspberry)
 (modules Intc Systimer Pl011 Miniuart Framebuffer Display Devices Usb Dwc2 Sdhost Dma Board)
 (flags (:standard -open Ix_machine))
 (libraries ix_machine))

(executable
 (name Main)
 (public_name tinypi)
 (package ix)
 (modules Main Sdl_display Qmp Storage)
 (flags (:standard -open Ix_machine))
 (libraries ix_raspberry ix_machine ix_core caps fpath unix tsdl yojson))
