(library
 (name ix_raspberry)
 (wrapped false)
 (modules Intc Systimer Pl011 Miniuart Framebuffer Display Devices Usb Usernet Dwc2 Sdhost Dma Board Gic Pi4 Prof Status)
 (libraries ix_machine ix_machine_compat unix))

(executable
 (name Main)
 (public_name mini-qemu)
 (package ix)
 (modules Main Sdl_display Qmp Storage)
 (libraries ix_raspberry ix_machine ix_core caps fpath unix tsdl))
