# mini-yacc, built by ix's tools
TOP=../..
DIR=generators/yacc
PROG=mini-yacc
SRC=Yacc Lalr Output CLI Main
GEN=
LIBI=
LIBUNITS=
LIBOBJS=
LOCAL=`{ls *.ml *.mli}
<$TOP/mkfiles/mkconfig
<$TOP/mkfiles/mkprog
